image: humourmind/tool-yugabytedb:test

tasks:
- name: disable-preload
  env:
    DB_PRELOAD="false"
  before: |
    echo "do nothing"

- name: shell
  command: |
    gp await-port 5433
    ysqlsh
# exposed ports
ports:
  - port: 7000
    onOpen: notify
  - port: 9000
    onOpen: notify
  - port: 37843
    onOpen: ignore
  - port: 7100
    onOpen: ignore
  - port: 9100
    onOpen: ignore
  - port: 5433
    onOpen: notify
  - port: 13000
    onOpen: ignore
  - port: 9042
    onOpen: notify
  - port: 12000
    onOpen: ignore

vscode:
  extensions:
    - GitHub.vscode-pull-request-github
