image: gitpod/workspace-yugabytedb-preview
# image: gitpod/workspace-yugabytedb

tasks:
  - name: check-base
    before: |
      yugabyted start --base_dir=$STORE/ybd1 --listen=$HOST --tserver_flags="placement_cloud=cloud1,placement_region=datacenter1,placement_zone=rack1" --master_flags="placement_cloud=cloud1,placement_region=datacenter1,placement_zone=rack1"
      gp sync-done base
  - name: run-ep2
    before: |
      gp sync-await base
      yugabyted start --base_dir=$STORE/ybd2 --listen=127.0.0.2 --join=$HOST --tserver_flags="placement_cloud=cloud1,placement_region=datacenter1,placement_zone=rack2" --master_flags="placement_cloud=cloud1,placement_region=datacenter1,placement_zone=rack2"
      gp sync-done ep2
  - name: run-ep3
    before: |
      gp sync-await base
      yugabyted start --base_dir=$STORE/ybd3 --listen=127.0.0.3 --join=$HOST --tserver_flags="placement_cloud=cloud1,placement_region=datacenter1,placement_zone=rack3" --master_flags="placement_cloud=cloud1,placement_region=datacenter1,placement_zone=rack3"
      gp sync-done ep3
  - name: cluster-config
    before: |
      gp sync-await ep3
      yb-admin -master_addresses $HOST:7100,127.0.0.2:7100,127.0.0.3:7100 modify_placement_info cloud1.datacenter1.rack1,cloud1.datacenter1.rack2,cloud1.datacenter1.rack3 3
  - name: shell
    command: |
      gp ports await 5433
      ysqlsh

# exposed ports
ports:
  - port: 7000
    onOpen: notify
  - port: 9000
    onOpen: notify
  - port: 37843
    onOpen: ignore
  - port: 7100
    onOpen: ignore
  - port: 9100
    onOpen: ignore
  - port: 5433
    onOpen: notify
  - port: 13000
    onOpen: ignore
  - port: 9042
    onOpen: notify
  - port: 12000
    onOpen: ignore

vscode:
  extensions:
    - GitHub.vscode-pull-request-github
