image: humourmind/tool-yugabytedb:test

tasks:
- name: disable-preload
  env:
    DB_PRELOAD="false"
  command: echo $DB_PRELOAD

# exposed ports
ports:
  - port: 7000
    onOpen: ignore
  - port: 9000
    onOpen: ignore
  - port: 37843
    onOpen: ignore
  - port: 7100
    onOpen: ignore
  - port: 9100
    onOpen: ignore
  - port: 5433
    onOpen: ignore
  - port: 13000
    onOpen: ignore
  - port: 9042
    onOpen: ignore
  - port: 12000
    onOpen: ignore
