image: gitpod/workspace-yugabytedb-preview

tasks:
  - name: check-base
    before: |
      yugabyted start --base_dir=$STORE/ybd1 --advertise_address=$HOST --cloud_location=cloud1.datacenter1.rack1 --fault_tolerance=zone
      gp sync-done base
  - name: run-ep2
    before: |
      gp sync-await base && gp ports await 7100
      yugabyted start --base_dir=$STORE/ybd2 --advertise_address=127.0.0.2 --join=$HOST --cloud_location=cloud1.datacenter1.rack2 --fault_tolerance=zone
      gp sync-done ep2
  - name: run-ep3
    before: |
      gp sync-await ep2
      yugabyted start --base_dir=$STORE/ybd3 --advertise_address=127.0.0.3 --join=$HOST --cloud_location=cloud1.datacenter1.rack3 --fault_tolerance=zone
      gp sync-done ep3
  - name: cluster-config
    before: |
      gp sync-await ep3
      yugabyted configure --base_dir=$STORE/ybd1 --fault_tolerance=zone
  - name: shell
    command: |
      gp ports await 5433
      ysqlsh

# exposed ports
ports:
  - port: 7000
    onOpen: notify
  - port: 9000
    onOpen: notify
  - port: 37843
    onOpen: ignore
  - port: 7100
    onOpen: ignore
  - port: 9100
    onOpen: ignore
  - port: 5433
    onOpen: notify
  - port: 13000
    onOpen: ignore
  - port: 9042
    onOpen: notify
  - port: 12000
    onOpen: ignore

vscode:
  extensions:
    - GitHub.vscode-pull-request-github