image:
  file: .gitpod.Dockerfile

tasks:
  - name: run-base
    before: |
      yugabyted start --base_dir=$STORE/ybd1 --advertise_address=$HOST_LB
      gp sync-done base
  - name: run-lb2
    before: |
      gp sync-await base
      yugabyted start --base_dir=$STORE/ybd2 --advertise_address=$HOST_LB2 --join=$HOST_LB
      gp sync-done lb2
  - name: run-lb3
    before: |
      gp sync-await lb2
      yugabyted start --base_dir=$STORE/ybd3 --advertise_address=$HOST_LB3 --join=$HOST_LB
  - name: shell
    command: |
      gp ports await 5433
      ysqlsh

# exposed ports
ports:
  - port: 7000
    onOpen: notify
  - port: 9000
    onOpen: notify
  - port: 37843
    onOpen: ignore
  - port: 7100
    onOpen: ignore
  - port: 9100
    onOpen: ignore
  - port: 5433
    onOpen: notify
  - port: 13000
    onOpen: ignore
  - port: 9042
    onOpen: notify
  - port: 12000
    onOpen: ignore

vscode:
  extensions:
    - GitHub.vscode-pull-request-github